### ISSUE TITLE
Some Symbol Token round trip conversion scenarios are lossy

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-dotnet#133]
There are some scenarios where Symbol Token round trip conversions are lossy. Valid SIDs get lost during text roundtrip conversions and the unknown SID is lost during a binary roundtrip conversion.

```c#
// Text writer/reader round trip conversion fails for SymbolToken with valid SID.

var inToken = new SymbolToken("symbol", 10);

var stream = new MemoryStream();
IIonWriter writer = IonTextWriterBuilder.Build(new StreamWriter(stream));

writer.WriteSymbolToken(inToken);
writer.Finish();
writer.Flush();
stream.Position = 0;

IIonReader reader = IonReaderBuilder.Build(stream, new ReaderOptions {Format = ReaderFormat.Detect});
reader.MoveNext();

var outToken = reader.SymbolValue();

Console.WriteLine($"Original SID: {inToken.Sid}, RoundTrip SID: {outToken.Sid}");


// Binary writer/reader round trip conversion fails for SymbolToken with unknown SID.

inToken = new SymbolToken("symbol", SymbolToken.UnknownSid);

stream = new MemoryStream();
writer = IonBinaryWriterBuilder.Build(stream);
writer.WriteSymbolToken(inToken);
writer.Finish();
writer.Flush();
stream.Position = 0;

reader = IonReaderBuilder.Build(stream, new ReaderOptions {Format = ReaderFormat.Detect});
reader.MoveNext();

outToken = reader.SymbolValue();

Console.WriteLine($"Original SID: {inToken.Sid}, RoundTrip SID: {outToken.Sid}");
```

**Comment by desaikd** [comment]
Hey justing-bq@,
Thanks for reaching out about this! This is not really an issue with `ion-dotnet`. According to [Ion equivalence](https://amzn.github.io/ion-docs/guides/symbols-guide.html#symboltoken-equivalence) `SymbolTokens` with the same text are equivalent. Hence for both the cases above `SymbolTokens` are still equivalent after roundtrips as they both have `"symbol"` as text in the `SymbolTokens`.

In the text case, the writer will emit the text `symbol` and is not likely to add that text to the symbol table. This means that the SID `10` doesn’t appear in the data stream and a reader won’t be able to infer it.

In the binary case, the writer must add the text `symbol` to the symbol table because the only way to encode a symbol is as a symbol ID. Hence the writer will write SID `10` to the data stream, and the reader will have to use the symbol table to discover its corresponding text. The reader will end up with `(text="symbol", SID=10)` and won’t know that the original `SymbolToken` had an unknown SID.

**Comment by zslayton** [comment]
I'm going to close this as we don't believe it's a problem. Feel free to re-open it if you disagree.
